// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvg6ZIQlkUjCvYL2j2XYi31lKT5d85n1g',
    appId: '1:1048238326855:web:1776a427642c7f42849d62',
    messagingSenderId: '1048238326855',
    projectId: 'congressrahul-8c6e3',
    authDomain: 'congressrahul-8c6e3.firebaseapp.com',
    storageBucket: 'congressrahul-8c6e3.appspot.com',
    measurementId: 'G-NVFKVTBNC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6tTfv1PEG0TC3Vl4W4YOjQOxC9S50rq8',
    appId: '1:1048238326855:android:cf58b4613def4291849d62',
    messagingSenderId: '1048238326855',
    projectId: 'congressrahul-8c6e3',
    storageBucket: 'congressrahul-8c6e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA69_lOWkeCXLTZteBfm4usx3w608S5ja4',
    appId: '1:1048238326855:ios:33b6ca33412d905c849d62',
    messagingSenderId: '1048238326855',
    projectId: 'congressrahul-8c6e3',
    storageBucket: 'congressrahul-8c6e3.appspot.com',
    iosBundleId: 'com.example.congressPolling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA69_lOWkeCXLTZteBfm4usx3w608S5ja4',
    appId: '1:1048238326855:ios:e4717d5cae9658f0849d62',
    messagingSenderId: '1048238326855',
    projectId: 'congressrahul-8c6e3',
    storageBucket: 'congressrahul-8c6e3.appspot.com',
    iosBundleId: 'com.example.congressPolling.RunnerTests',
  );
}
